---
- hosts: volvuntu
  gather_facts: yes

  vars_files:
    - vars/main.yml

  tasks:
    - name: "==> Set remote_user if needed"
      set_fact:
        remote_user: "{{ ansible_ssh_user }}"
      when: remote_user is not defined

    - name: "==> Install Hardware Enablement package"
      include_role:
        name: itnok.manage_pkg_ubuntu
      vars:
        manage_pkg_app_install_recommends: yes
        manage_pkg_app:
          - "linux-generic-hwe-18.04"

    - name: "==> Install Docker"
      include_role:
        name: itnok.manage_pkg_ubuntu
      vars:
        install_dependency:
          - "apt-transport-https"
          - "ca-certificates"
          - "curl"
          - "gnupg-agent"
          - "software-properties-common"
        manage_pkg_dependency: "{{ __manage_pkg_dependency + install_dependency }}"
        manage_pkg_key:
          - "https://download.docker.com/linux/ubuntu/gpg"
        manage_pkg_repo:
          - "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        manage_pkg_app:
          - "docker-ce"

    - name: "Adding existing user '{{ remote_user }}' to group 'docker'"
      user:
        name: "{{ remote_user }}"
        groups: docker
        append: yes

    - name: "==> Upgrade the whole OS & all packages"
      include_role:
        name: itnok.update_ubuntu

    - name: "==> Install Ubuntu Desktop"
      include_role:
        name: itnok.manage_pkg_ubuntu
      vars:
        manage_pkg_app:
          - "ubuntu-desktop"

    - name: "==> Install xserver HWE optimization"
      include_role:
        name: itnok.manage_pkg_ubuntu
      vars:
        manage_pkg_app_install_recommends: yes
        manage_pkg_app:
          - "xserver-xorg-hwe-18.04"

    - name: "==> Upgrade the whole OS & all packages"
      include_role:
        name: itnok.update_ubuntu

    - name: "==> Install SDDM login manager"
      include_role:
        name: itnok.manage_pkg_ubuntu
      vars:
        install_dependency:
          - "qml-module-qtquick-controls"
          - "qml-module-qtquick-layouts"
        manage_pkg_dependency: "{{ __manage_pkg_dependency + install_dependency }}"
        manage_pkg_app:
          - "sddm"

    - name: "Download Chili SDDM theme"
      get_url:
        url: "https://github.com/MarianArlt/sddm-chili/archive/0.1.5.tar.gz"
        dest: "/tmp/sddm-chili.tar.gz"
        checksum: "sha256:a3c0607bf70f448fff0a271624e3bc15af978894c04c98355d00a57431e49a0f"

    - name: "Make sure '/usr/share/sddm/themes/chili' directory exists"
      file:
        path: "/usr/share/sddm/themes/chili"
        state: directory
        owner: root
        group: root

    - name: "Install Chili theme for SDDM"
      unarchive:
        src: "/tmp/sddm-chili.tar.gz"
        dest: "/usr/share/sddm/themes/chili"
        remote_src: yes
        extra_opts:
          - "--strip-components"
          - "1"

    - name: "Set Chili as default SDDM theme"
      ini_file:
        path: "/etc/sddm.conf"
        section: "Theme"
        option: "Current"
        value: "chili"
        state: present
        backup: yes

    # - name: "Restart SDDM to apply configuration changes"
    #   service:
    #     name: sddm
    #     state: restarted

    - name: "==> Uninstall GDM3 login manager"
      include_role:
        name: itnok.manage_pkg_ubuntu
      vars:
        manage_pkg_app_do: "absent"
        manage_pkg_app:
            - "gdm3"

    - name: "==> Install Cinnamon"
      include_role:
        name: itnok.manage_pkg_ubuntu
      vars:
        install_dependency:
          - "dconf-tools"
          - "python3-psutil"
        manage_pkg_dependency: "{{ __manage_pkg_dependency + install_dependency }}"
        manage_pkg_repo:
          - "ppa:embrosyn/cinnamon"
        manage_pkg_app:
          - "cinnamon"

    - name: "==> Install Cinnamon customizations"
      include_role:
        name: itnok.manage_pkg_ubuntu
      vars:
        manage_pkg_repo:
          - "ppa:noobslab/macbuntu"
        manage_pkg_app:
          - "macbuntu-os-icons-v1804"
          - "macbuntu-os-ithemes-v1804"
          - "macbuntu-os-plank-theme-v1804"
          - "plank"

    - name: "Customize Cinnamon UI"
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key: "/org/cinnamon/panels-height", value: [ "1:24" ] }
        - { key: "/org/cinnamon/alttab-switcher-delay", value: "100" }
        - { key: "/org/cinnamon/panel-edit-mode", value: "false" }
        - { key: "/org/cinnamon/enabled-applets", value: [ "panel1:left:1:menu@cinnamon.org:0", "panel1:right:4:systray@cinnamon.org:3", "panel1:right:12:notifications@cinnamon.org:4", "panel1:right:6:keyboard@cinnamon.org:7", "panel1:right:5:network@cinnamon.org:9", "panel1:right:7:sound@cinnamon.org:10", "panel1:right:9:power@cinnamon.org:11", "panel1:right:10:calendar@cinnamon.org:12", "panel1:left:2:spacer@cinnamon.org:13", "panel1:left:0:spacer@cinnamon.org:14", "panel1:right:13:spacer@cinnamon.org:15", "panel1:right:11:spacer@cinnamon.org:17", "panel1:right:8:spacer@cinnamon.org:18", "panel1:right:2:spacer@cinnamon.org:19" ] }
        - { key: "/org/cinnamon/alttab-minimized-aware", value: "true" }
        - { key: "/org/cinnamon/next-applet-id", value: "21" }
        - { key: "/org/cinnamon/enabled-desklets", value: "@as []" }
        - { key: "/org/cinnamon/alttab-switcher-style", value: "'icons'" }
        - { key: "/org/cinnamon/hotcorner-layout", value: [ "expo:false:0", "scale:false:0", "scale:false:0", "desktop:false:0" ] }
        - { key: "/org/cinnamon/panel-zone-icon-sizes", value: '[{"panelId": 1, "left": 22, "center": 0, "right": 0}]' }
        - { key: "/org/cinnamon/alttab-switcher-show-all-workspaces", value: "true" }
        - { key: "/org/cinnamon/applet-cache-updated", value: "0" }
        - { key: "/org/cinnamon/panels-enabled", value: [ "1:0:top" ] }

        - { key: "/org/cinnamon/muffin/resize-threshold", value: "24" }

        - { key: "/org/cinnamon/desktop/background/slideshow/image-source", value: "'directory:///~/Pictures'" }
        - { key: "/org/cinnamon/desktop/background/slideshow/delay", value: "15" }

        - { key: "/org/cinnamon/desktop/interface/icon-theme", value: "'MacBuntu-OSX'" }
        - { key: "/org/cinnamon/desktop/interface/cursor-theme", value: "'Macbuntu-OSX-cursors'" }
        - { key: "/org/cinnamon/desktop/interface/gtk-theme", value: "'MacBuntu-Sierra-dark-solid'" }

        - { key: "/org/cinnamon/desktop/sound/event-sounds", value: "false" }

        - { key: "/org/cinnamon/desktop/wm/preferences/min-window-opacity", value: "30" }
        - { key: "/org/cinnamon/desktop/wm/preferences/button-layout", value: "'close,minimize,maximize:'" }
        - { key: "/org/cinnamon/desktop/wm/preferences/theme", value: "'MacBuntu-Sierra-dark'" }

        - { key: "/org/cinnamon/theme/symbolic-relative-size", value: "0.75" }
        - { key: "/org/cinnamon/theme/theme-cache-updated", value: "0" }
        - { key: "/org/cinnamon/theme/name", value: "'MacBuntu-OS-3.2-High-Sierra-Dark-master'" }

    - name: "==> Install Mesa"
      include_role:
        name: itnok.manage_pkg_ubuntu
      vars:
        manage_pkg_repo:
          - "ppa:kisak/kisak-mesa"

    - name: "==> Upgrade the whole OS & all packages"
      include_role:
        name: itnok.update_ubuntu
